version: '3'
services:
  webcaptioner-ng-back:
    image: webcaptioner-ng-back:latest
    restart: unless-stopped
    environment:
      - WEBCAPTIONER_BACKEND_PORT
      - SOTRA_SERVER_CTRANSLATE_URL
      - SOTRA_SERVER_FAIRSEQ_URL
      - VOSK_SERVER_URL
      - MONGODB_URI
      - JWT_SECRET_KEY
#    ports:
#        - '80:4000'
