version: '3'
services:
  webcaptioner-ng-back:
    image: webcaptioner-ng-back:latest
    user: "1000:1000"
    restart: unless-stopped
    environment:
        - WEBCAPTIONER_BACKEND_PORT
        - SOTRA_SERVER_CTRANSLATE_URL
        - SOTRA_SERVER_FAIRSEQ_URL
        - CONFIG
        - MONGODB_USERNAME
        - MONGODB_PASSWORD
        - MONGODB_HOST
        - JWT_SECRET_KEY
        - FREE_PASSWORD
        - BAMBORAK_SERVER
        - DB_ADMIN_FIRSTNAME
        - DB_ADMIN_LASTNAME
        - DB_ADMIN_EMAIL
        - DB_ADMIN_PASSWORD
        - KEYCLOAK_URL
        - KEYCLOAK_REALM
        - KEYCLOAK_CLIENT_ID
        - KEYCLOAK_CLIENT_SECRET
        - KEYCLOAK_SERVICE_ACCOUNT_CLIENT_ID
        - KEYCLOAK_SERVICE_ACCOUNT_CLIENT_SECRET
        - KEYCLOAK_ADMIN_ROLE
#    volumes:
#        - ../config:/app/config
#    ports:
#        - '80:4000'
